// Tampilan v2 — disesuaikan dengan mockup PRD (dimuat setelah app.js)
const VIL='Karangpari',logo=s=>`<span class="logo" style="--s:${s||34}px">⚖</span>`,pct=(a,b)=>b?Math.round(a/b*100):0;
const sc2=(l,n,s,c)=>`<div class="st" style="--c:${c}"><small>${l}</small><b>${n}</b><span>${s||''}</span></div>`;
const ph=(chip,t,sub,r)=>`<div class="ph"><div>${chip?`<span class="chip">${chip}</span>`:''}<h1>${t}</h1><p>${sub}</p></div><div class="phr">${r||''}</div></div>`;
const grpC=()=>{const j=by('jenis');return{p:j.Perdes||0,k:j.Perkades||0,s:j['SK Kades']||0,x:S.docs.filter(d=>d.tingkat!=='Desa').length}};
const nl=k=>([h,t,c])=>`<a href="#/${h}" class="${h===k?'on':''}">${t}${c?`<i>${c}</i>`:''}</a>`;
side=function(k){$('#side').innerHTML=S.user?`<div class="brand">${logo(40)}<div><b>e-REGDESA</b><small>Kab. Banyumas - Desa ${VIL}</small></div></div><div class="lb">MENU UTAMA</div>`+[['dash','Dashboard'],['reg','Register Dokumen'],['add','Tambah Dokumen'],['incomplete','Dokumen Belum Lengkap',S.docs.filter(d=>!d.fileUrl).length],['export','Ekspor Laporan']].map(nl(k)).join('')+`<div class="lb">INTEGRASI EKSTERNAL</div>`+nl(k)(['pub','Portal Publik'])+`<div class="ufoot"><div><b>${esc(S.user.name)}</b><small>Petugas Desa</small></div><button onclick="logout()" title="Keluar">⎋</button></div>`:''};
hdr=function(){$('#auth').innerHTML=S.user?`<span class="chip2">📅 ${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'short',year:'numeric'})}</span><input class="gs" placeholder="Cari nomor perdes / regulasi…" onkeydown="if(event.key==='Enter'){S.q.t=this.value;location.hash==='#/reg'?render():location.hash='#/reg'}"><span class="av">${esc(S.user.name[0])}</span>`:'<a class="tabx" href="#/pub">Beranda Publik</a><a class="btn1" href="#/login">🔒 Masuk Petugas</a>';
  $('.top').firstElementChild.innerHTML=`${logo(30)} <b>e-REGDESA</b> <small>/ ${S.user?'Administrasi Hukum Desa':'Jaringan Dokumentasi & Informasi Hukum Desa'}</small>`;
  if($('#gbtn')&&window.google?.accounts)google.accounts.id.renderButton($('#gbtn'),{theme:'filled_black',size:'large',width:320,text:'signin_with'})};
removeEventListener('hashchange',render);
render=function(){const[r,a]=location.hash.slice(2).split('/');let k=r||(S.user?'dash':'pub');if(!R[k]||(!S.user&&!['pub','doc','login'].includes(k)))k='pub';if(S.user&&k==='login')k='dash';
  document.body.classList.toggle('pubmode',!S.user);document.body.classList.toggle('lgin',k==='login');S.adm=!!S.user&&k!=='pub';
  $('#app').innerHTML=!S.docs.length&&!S.loaded&&k!=='login'?'<p>Memuat data…</p>':R[k](a);side(k);hdr()};
addEventListener('hashchange',render);
const filt0=filt,list0=list;filt=()=>filt0().filter(d=>!S.q.sup||d.tingkat!=='Desa');
clr=k=>{S.q[k]='';render()};tabx=(k,v)=>{S.q.sup=k==='sup'?'1':'';S.q.jenis=k==='sup'?'':v;S.pg=1;render()};
list=adm=>{const ch=[['t','Kata kunci'],['jenis','Jenis'],['tahun','Tahun'],['status','Status']].filter(([k])=>S.q[k]).map(([k,l])=>`<span class="chip">${l}: ${esc(S.q[k])} <a href="#" onclick="clr('${k}');return false">×</a></span>`).join('');
  return list0(adm).replace('<div id="res">',`<div class="chips">${ch?'Penyaring Aktif: '+ch+'<a href="#" onclick="S.q={t:\'\',jenis:\'\',tahun:\'\',status:\'\'};render();return false">Hapus Semua</a>':''}</div><div id="res">`)};

R.dash=function(){const D=S.docs,n=D.length,c=grpC(),j=by('jenis'),yr=by('tahun'),ys=Object.keys(yr).sort(),mx=Math.max(1,...Object.values(yr)),cy=String(new Date().getFullYear()),st=by('status'),tg=by('tingkat'),nf=D.filter(d=>!d.fileUrl).length,nas=tg.Nasional||0,dae=(tg.Provinsi||0)+(tg.Kabupaten||0),des=tg.Desa||0;
  const pie=[['Peraturan Desa (Perdes)',c.p,'#1B4332'],['SK Kepala Desa',c.s,'#795900'],['Peraturan Kades',c.k,'#3f6653'],['Lainnya',n-c.p-c.s-c.k,'#FFC641']];let a=0;const cg=pie.map(([,v,col])=>{const s=a;a+=v/(n||1)*360;return`${col} ${s}deg ${a}deg`}).join(',');
  return `<div class="hero"><div><span class="chip">SISTEM REGISTRASI DOKUMEN HUKUM DESA</span><h1>Selamat Bertugas, ${esc(S.user.name)}</h1><p>Tersedia <b>${n} dokumen regulasi</b> tersimpan dalam master register digital Desa ${VIL}.</p></div><div class="cal"><small>KALENDER KERJA RESMI</small><b>${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b></div></div>
${nf?`<div class="alert"><div><b>Perhatian: Ada ${nf} dokumen regulasi belum memiliki berkas digital PDF di Google Drive.</b><br><small>Kelengkapan naskah digital penting untuk menjamin legalitas publikasi dan integrasi JDIH.</small></div><a class="btn3" href="#/incomplete">Tindak Lanjuti & Unggah Berkas →</a></div>`:''}
<div class="g6">${sc2('TOTAL DOKUMEN',n,'Arsip terdaftar','#1B4332')}${sc2('PERATURAN DESA',c.p,pct(c.p,n)+'% dari total','#795900')}${sc2('PERKADES',c.k,'Peraturan operasional','#3f6653')}${sc2('SK KADES',c.s,'Ketetapan penetapan','#795900')}${sc2('REGULASI DAERAH',dae,'Perda & Perbup rujukan','#6D28D9')}${sc2('REGULASI NASIONAL',nas,'UU & PP Pedoman','#1D4ED8')}</div>
<div class="g2"><div class="card"><h3>Tren Penerbitan Regulasi per Tahun</h3><div class="bars">${ys.map(y=>`<div>${yr[y]}<span style="height:${yr[y]/mx*110}px;${y===cy?'background:#FFC641':''}"></span>${y}</div>`).join('')}</div></div>
<div class="card"><h3>Proporsi Jenis Produk Hukum</h3><div class="pie"><div class="donut" style="background:conic-gradient(${cg})"><div><b>${n}</b><small>PRODUK</small></div></div><ul>${pie.map(([l,v,col])=>`<li><i style="background:${col}"></i>${l}<b>${v}</b><small>(${pct(v,n)}%)</small></li>`).join('')}</ul></div></div></div>
<div class="g2"><div class="card"><h3>Komposisi Tingkat Regulasi</h3><div class="stk"><span style="width:${pct(des,n)}%;background:#1B4332">${pct(des,n)}% Tingkat Desa</span><span style="width:${pct(dae,n)}%;background:#FFC641"></span><span style="flex:1;background:#6b7280"></span></div><div class="g3"><div class="mini"><small>TINGKAT DESA</small><b>${des}</b></div><div class="mini"><small>PROV / KAB</small><b>${dae}</b></div><div class="mini"><small>NASIONAL</small><b>${nas}</b></div></div></div>
<div class="card"><h3>Status Keberlakuan Hukum</h3>${[['Berlaku','Berlaku Penuh','#166534'],['Dicabut','Dicabut / Diganti','#991B1B'],['Tidak Berlaku','Kadaluarsa / Habis Masa','#FFC641']].map(([k,l,col])=>`<p class="sr"><span><i style="background:${col}"></i>${l}</span><b>${st[k]||0} dokumen (${pct(st[k]||0,n)}%)</b></p><div class="pb"><span style="width:${pct(st[k]||0,n)}%;background:${col}"></span></div>`).join('')}</div></div>
<div class="card"><div class="ch"><h3>5 Regulasi Terbaru Ditetapkan</h3><span><button class="b1" onclick="location.hash='#/add'">+ Tambah Dokumen Baru</button> <button class="b2" onclick="location.hash='#/reg'">Buka Semua Register ↗</button></span></div>${tbl(filt().slice(0,5))}<small>Menampilkan 5 regulasi dari ${n} entri registrasi</small></div>`};

R.reg=function(){const n=S.docs.length,b=S.docs.filter(d=>d.status==='Berlaku').length,e=S.docs.filter(d=>d.status==='Tidak Berlaku').length,nf=S.docs.filter(d=>!d.fileUrl).length;
  return ph('DATABASE JDIH DESA MANDIRI','Register Produk Hukum & Regulasi Desa','Inventaris resmi dan arsip legalitas seluruh peraturan desa, keputusan kepala desa, serta regulasi supradesa yang mengikat yurisdiksi Desa '+VIL+'.','<button class="b2" onclick="location.hash=\'#/export\'">⭳ Ekspor Data</button><button class="b1" onclick="location.hash=\'#/add\'">+ Tambah Peraturan Baru</button>')+`<div class="g4">${sc2('Total Regulasi Terdaftar',n,'','#1B4332')}${sc2('Status Berlaku Penuh',b,pct(b,n)+'%','#0d9488')}${sc2('Perlu Evaluasi / Kadaluwarsa',e,'Prioritas','#795900')}${sc2('Berkas Digital Kosong',nf,'Unggah PDF','#991B1B')}</div>`+list(true)};

R.pub=function(){const c=grpC(),tab=(l,k,v)=>`<button class="tab ${(k==='sup'?S.q.sup:!S.q.sup&&S.q.jenis===v)?'on':''}" onclick="tabx('${k}','${v}')">${l}</button>`;
  return `<div class="phero">${logo(60)}<br><span class="chip">PORTAL RESMI JDIH PUBLIK TINGKAT DESA</span><h1>Jaringan Dokumentasi & Informasi Hukum (JDIH) Desa ${VIL}</h1><p>Transparansi Regulasi dan Akses Produk Hukum Terbuka bagi Seluruh Warga Desa ${VIL}.</p><div class="sbox"><input placeholder="Ketik kata kunci peraturan, contoh: BLT Dana Desa, APBDes 2026" value="${esc(S.q.t)}" oninput="setQ('t',this.value)"><button class="b1" onclick="$('#res').scrollIntoView({behavior:'smooth'})">Cari Peraturan</button></div></div>
<div class="g4">${sc2('Peraturan Desa (Perdes)',c.p,'Ketetapan Hukum Sah','#1B4332')}${sc2('Peraturan Kades (Perkades)',c.k,'Petunjuk Pelaksanaan','#0d9488')}${sc2('SK Kepala Desa',c.s,'Ketetapan Penetapan','#795900')}${sc2('Regulasi Supradesa',c.x,'Rujukan UU & Perda','#1D4ED8')}</div>
<div class="tabs">${tab('Semua Produk Hukum','jenis','')}${tab('Peraturan Desa','jenis','Perdes')}${tab('Peraturan Kepala Desa','jenis','Perkades')}${tab('Surat Keputusan (SK)','jenis','SK Kades')}${tab('Regulasi Nasional/Daerah','sup','1')}</div>`+list(false)+`<div class="pubf"><b>Keterbukaan Informasi Publik Desa</b><p>Setiap warga berhak memperoleh salinan dan menelaah naskah regulasi desa sesuai UU No. 14 Tahun 2008 tentang Keterbukaan Informasi Publik.</p></div>`};

R.login=()=>`<div class="lg"><div class="lgc">${logo(70)}<br><span class="chip">JDIH DESA ${VIL.toUpperCase()}</span><h1>e-REGDESA</h1><p>Sistem Informasi Regulasi dan Produk Hukum Desa</p><div class="note">📍 Desa ${VIL}, Kec. Cilongok, Kab. Banyumas</div><div class="note"><b>Akses Terbatas:</b> Ditujukan khusus bagi Sekretaris Desa dan Kaur TU & Umum menggunakan Akun Google Workspace Resmi Pemerintah Desa.</div><div id="gbtn" style="display:flex;justify-content:center;margin:16px 0"></div><hr><b>Masyarakat Umum & Warga Desa</b><a class="tele" href="#/pub"><b>Telusuri Produk Hukum Sebagai Warga →</b><br><small>Akses Perdes, Perkades, & SK Kades (Tanpa Login)</small></a><small class="fp">Berdasarkan Permendagri No. 111/2014 & UU No. 6/2014 tentang Desa.</small></div></div>`;

function form2(d){const e=!!d,x={tahun:new Date().getFullYear(),penerbit:'Pemerintah Desa '+VIL,status:'Berlaku',...(d||JSON.parse(localStorage.eg_draft||'{}'))},v=k=>esc(x[k]??''),tg=x.tingkat||'Desa';
  const f=(l,n,t,w)=>`<label class="${w||''}">${l}<input name="${n}" type="${t||'text'}" ${l.includes('*')?'required':''} value="${t==='date'?esc(String(x[n]||'').slice(0,10)):v(n)}"></label>`,ta=(l,n)=>`<label class="w">${l}<textarea name="${n}">${v(n)}</textarea></label>`,sec=(n,t,b)=>`<div class="sec"><h4><i></i>${n}. ${t}</h4><div class="fg">${b}</div></div>`;
  return `<div class="crumb">Register Dokumen › ${e?'Edit':'Tambah'} Dokumen</div><h1>${e?'Edit Dokumen':'Formulir Inventarisasi Produk Hukum Baru'}</h1><p>Pencatatan naskah hukum, metadata legalitas, dan digitalisasi arsip lembaran desa terpusat.</p><div class="note"><b>Instruksi Validitas Administrasi</b> <span class="chip g">Wajib Dipatuhi</span><br>Pastikan seluruh data sesuai naskah asli lembaran desa yang telah ditandatangani Kepala Desa dan diundangkan dalam Berita Desa.</div>
<form class="card" onsubmit="save(event,'${e?esc(d.id):''}')" oninput="draft(this,${e})">`+
  sec(1,'KLASIFIKASI HUKUM',`<label>Tingkat Regulasi*<select name="tingkat" onchange="this.form.jenis.innerHTML=opt(JENIS[this.value])">${opt(TING,tg)}</select></label><label>Jenis Produk Hukum*<select name="jenis">${opt(JENIS[tg],x.jenis)}</select></label>`)+
  sec(2,'IDENTITAS DOKUMEN',f('Nomor Dokumen*','nomor')+f('Tahun Penerbitan*','tahun','number')+f('Tanggal Penetapan*','tglPenetapan','date')+f('Tanggal Pengundangan (Opsional)','tglPengundangan','date')+f('Instansi / Pejabat Penerbit*','penerbit')+f('Judul Lengkap Peraturan*','judul','text','w')+ta('Pokok-Pokok Peraturan / Tentang','tentang'))+
  sec(3,'STATUS KEBERLAKUAN & DASAR HUKUM',`<div class="w"><small>Status Keberlakuan*</small><br>${STATUS.map(s=>`<label class="seg"><input type="radio" name="status" value="${s}" ${x.status===s?'checked':''}>${s}</label>`).join('')}<label class="seg"><input type="checkbox" name="perubahan" value="Ya" ${x.perubahan==='Ya'?'checked':''}>Regulasi Amandemen / Pengganti</label></div>`+ta('Dasar Hukum Konsiderans (Mengingat)','dasarHukum')+f('Lokasi Arsip Fisik','lokasiArsip','text','w')+ta('Keterangan Tambahan','keterangan'))+
  sec(4,'UNGGAH BERKAS DIGITAL (DRIVE STORAGE)',`<label class="drop w" ondragover="event.preventDefault()" ondrop="event.preventDefault();const i=this.querySelector('input');i.files=event.dataTransfer.files;i.dispatchEvent(new Event('change'))">☁<br><b>Tarik dan letakkan berkas PDF resmi di sini, atau klik untuk memilih file</b><small>Format: 1 berkas PDF bertanda tangan sah (maks. 10 MB). Otomatis disinkronkan ke Google Drive Desa.</small><input type="file" name="file" accept="application/pdf" hidden onchange="$('#fn').textContent=this.files[0]?'📄 '+this.files[0].name+' ('+(this.files[0].size/1048576).toFixed(1)+' MB)':''"><em id="fn">${x.fileUrl?'Berkas sudah tersimpan di Drive; pilih file baru untuk mengganti.':''}</em></label>`)+
  `<div class="abar"><a href="#/reg">← Batal & Kembali</a><span><button type="button" class="b2" onclick="draft(this.form,false);toast('Draft tersimpan')">Simpan ke Draft</button> <button class="b1">${e?'Simpan Perubahan':'Simpan & Publikasikan ke Register'}</button></span></div></form>`}
R.add=()=>form2();R.edit=id=>form2(S.docs.find(d=>d.id===id));

R.doc=function(id){const d=S.docs.find(x=>x.id===id);if(!d)return'<p>Dokumen tidak ditemukan. <a href="#/reg">Kembali</a></p>';
  const r=(a,b)=>`<tr><th>${a}</th><td>${esc(b)||'-'}</td></tr>`,ah=String(d.dasarHukum||'').split(/\n|;/).map(s=>s.trim().replace(/^\d+\.\s*/,'')).filter(Boolean),pv=String(d.fileUrl||'').replace(/\/view.*$/,'/preview');
  return `<div class="crumb"><a href="#/${S.user?'reg':'pub'}">← Kembali ke Register</a></div><div class="card dh"><div>${badge(d.status,sc[d.status])} ${badge('Tingkat: '+d.tingkat,tc[d.tingkat])} ${badge('Jenis: '+d.jenis)} <span class="chip mono">ID: ${esc(d.id)}</span><h1>${esc(d.judul)}</h1></div>${S.adm?`<span><a class="b2 btn" href="#/edit/${esc(d.id)}">Edit Dokumen</a> <button class="b2 er" onclick="del('${esc(d.id)}')">Hapus Dokumen</button></span>`:''}</div>
<div class="g21"><div><div class="card"><h3>Ringkasan Pokok Regulasi & Substansi</h3><p>${esc(d.tentang)||'-'}</p></div><div class="card"><h3>Data Legalitas & Pengesahan</h3><table class="kv">${r('ID Registrasi Master',d.id)}${r('Tahun Pengesahan',d.tahun)}${r('Tanggal Penetapan',fmt(d.tglPenetapan))}${r('Tanggal Pengundangan',fmt(d.tglPengundangan))}${r('Pemrakarsa / Pejabat Penerbit',d.penerbit)}${r('Status Keberlakuan',d.status)}${r('Riwayat Dokumen',d.perubahan==='Ya'?'Perubahan / Pengganti':'Dokumen Induk')}</table></div><div class="card"><h3>Dasar Hukum Konsiderans (Mengingat)</h3>${ah.map((t,i)=>`<div class="dh1"><i>${i+1}</i>${esc(t)}</div>`).join('')||'-'}</div>${S.user&&d.lokasiArsip?`<div class="card note">📍 <b>Catatan Penyimpanan Arsip Fisik</b><br>${esc(d.lokasiArsip)}</div>`:''}</div>
<div><div class="card"><h3>Berkas Digital Resmi</h3>${d.fileUrl?`<iframe class="pdf" src="${url(pv)}"></iframe><a class="b1 btn w" href="${url(d.fileUrl)}" target="_blank" rel="noopener">Buka / Pratinjau Penuh</a>`:'<p class="er">Belum ada berkas PDF.</p>'}</div>${S.user?`<div class="card"><h3>Jejak Audit</h3><p><small>Diinput oleh</small><br>${esc(d.diinputOleh)} · ${fmt(d.tglInput)}</p><p><small>Terakhir diubah</small><br>${fmt(d.terakhirDiubah)}</p></div>`:''}</div></div>`};

R.incomplete=function(){const r=S.docs.filter(d=>!d.fileUrl),i=(t,b)=>`<div class="card"><b>${t}</b><p><small>${b}</small></p></div>`;
  return ph('<span class="er">● Perlu Tindak Lanjut Digitalisasi</span>','Inventarisasi Dokumen Belum Memiliki Berkas Digital',`Daftar ${r.length} produk hukum yang telah teregistrasi dalam master data namun belum diunggah naskah digital PDF resminya ke Google Drive.`,`<div class="mini"><b>${r.length}</b><small>Total Tertunda</small></div>`)+`<div class="alert"><div><b>Perhatian Administrasi Hukum</b><br><small>${r.length} regulasi memerlukan digitalisasi arsip fisik agar dapat dipublikasikan ke Portal Warga dan disinkronkan ke JDIH Kabupaten. Pastikan hasil scan PDF jelas dan berkekuatan hukum.</small></div></div>
<div class="card tw"><table><thead><tr><th>No</th><th>Nomor & Tahun</th><th>Judul / Nomenklatur Regulasi</th><th>Jenis</th><th>Tgl Ditetapkan</th><th>Lokasi Arsip Fisik</th><th>Aksi</th></tr></thead><tbody>${r.map((d,n)=>`<tr><td>${n+1}</td><td><b>${esc(d.jenis)} No. ${esc(d.nomor)}</b> Th ${esc(d.tahun)}<br><small class="er">⊘ Naskah digital kosong</small></td><td><b>${esc(d.judul)}</b></td><td>${badge(d.jenis,tc[d.tingkat])}</td><td>${fmt(d.tglPenetapan)}</td><td>${d.lokasiArsip?`<span class="chip">📁 ${esc(d.lokasiArsip)}</span>`:'-'}</td><td><a href="#/edit/${esc(d.id)}">Unggah PDF</a></td></tr>`).join('')||'<tr><td colspan="7">Semua dokumen sudah memiliki berkas PDF. 🎉</td></tr>'}</tbody></table></div>
<div class="g3">${i('Standar Scan TTE','Gunakan resolusi minimal 300 DPI berformat PDF/A agar stempel dan tanda tangan basah terbaca jelas.')}${i('Sinkronisasi Cloud Drive','Berkas tersimpan di folder aman Google Drive Workspace Pemerintah Desa.')}${i('Kearsipan Fisik','Setelah berkas terunggah, pastikan kode identifikasi tercantum pada punggung lemari odner.')}</div>`};
render();
